services:
  python-ollama:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - OLLAMA_HOST=0.0.0.0
    ports:
      - "11434:11434"
    stdin_open: true
    tty: true
